const movies = [
  { name: "Forrest Gump", emoji: "🏃🍫🍤" },
  { name: "The Matrix", emoji: "🕶️💊👽" },
  { name: "Titanic", emoji: "🚢❄️💔" },
  { name: "Jurassic Park", emoji: "🦖🌴🚙" },
  { name: "The Lion King", emoji: "🦁👑🌅" },
  { name: "Star Wars", emoji: "⚔️🚀🌌" },
  { name: "The Avengers", emoji: "🦸‍♂️🦸‍♀️💥" },
  { name: "Harry Potter", emoji: "⚡🧙‍♂️🔮" },
  { name: "The Terminator", emoji: "🤖🔫🕶️" },
  { name: "Indiana Jones", emoji: "🤠🔍💎" },
  { name: "Back to the Future", emoji: "⏰🚗💥" },
  { name: "The Shawshank Redemption", emoji: "🔒🔑💰" },
  { name: "The Godfather", emoji: "🍕🤵🔫" },
  { name: "The Dark Knight", emoji: "🦇♞👨‍🦯" },
  { name: "Pulp Fiction", emoji: "🍔🔫🕶️" },
  { name: "Schindler's List", emoji: "📜🚂🔴" },
  { name: "The Lord of the Rings", emoji: "🧝‍♂️🧙‍♂️🗡️" },
  { name: "The Silence of the Lambs", emoji: "🔇🐑🍖" },
  { name: "Fight Club", emoji: "👊💼🚽" },
  { name: "Inception", emoji: "🌀👩‍🚀🎩" },
  { name: "The Sixth Sense", emoji: "👦👻🔮" },
  { name: "The Shining", emoji: "👦👩🪓" },
  { name: "The Exorcist", emoji: "👧😈📖" },
  { name: "The Blair Witch Project", emoji: "🌲👧🎥" },
  { name: "The Texas Chain Saw Massacre", emoji: "🔪🩸🏚️" },
  { name: "A Nightmare on Elm Street", emoji: "🛌🔪👨‍👦" },
  { name: "The Ring", emoji: "📞📼👧" },
  { name: "The Conjuring", emoji: "👻👩‍👦🔮" },
  { name: "The Babadook", emoji: "📖👦👹" },
  { name: "The Witch", emoji: "🐐👧🔮" },
  { name: "Get Out", emoji: "👦👩🔪" },
  { name: "Hereditary", emoji: "👵👧🔮" },
  { name: "A Quiet Place", emoji: "👨‍👩‍👧🔇" },
  { name: "The Invisible", emoji: "👦👧👻" },
  { name: "Eternal Sunshine of the Spotless Mind", emoji: "🌞🧠❤️" },
  { name: "Blade Runner", emoji: "🤖🏙️🔫" },
  { name: "Inglourious Basterds", emoji: "🔪🎥🔥" },
  { name: "The Grand Budapest Hotel", emoji: "🏨🎩🌸" },
  { name: "Pan's Labyrinth", emoji: "👧🌲👹" },
  { name: "The Social Network", emoji: "👥💻🌐" },
  { name: "Lost in Translation", emoji: "🗺️🗣️🎥" },
  { name: "The Big Lebowski", emoji: "🕶️🎳🥃" },
  { name: "Amélie", emoji: "🎻📸🌼" },
  { name: "The Departed", emoji: "🕵️‍♂️🔫👥" },
  { name: "Whiplash", emoji: "🥁🎶👊" },
  { name: "The Revenant", emoji: "🐻❄️🏔️" },
  { name: "Birdman", emoji: "🦅🎭🎥" },
  { name: "No Country for Old Men", emoji: "🌵💀💰" },
  { name: "Drive", emoji: "🚗🌆🔪" },
  { name: "Moonlight", emoji: "🌕🌈👦" },
  { name: "Her", emoji: "👨‍💻📱❤️" },
  { name: "The Prestige", emoji: "🎩🔮🎭" },
  { name: "The Truman Show", emoji: "🌎📺🎥" },
  { name: "A Beautiful Mind", emoji: "🧠📈❤️" },
];

export default movies;
